parameters:
#    acme_o_auth_server.example.class: Acme\OAuthServerBundle\Example

services:
#    acme_o_auth_server.example:
#        class: %acme_o_auth_server.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
